### ISSUE TITLE
Any update on code release time frame?

### ISSUE THREAD

**Issue by kentsommer** [gidariss/DRR_struct_pred#1]
Excited about your results, looking forward to playing with it when it becomes available!

**Comment by ChandrahasJR** [comment]
@gidariss Great paper! Eagerly looking forward to the code. Any update on the release date ?

**Comment by zhangguanghui1** [comment]
Eagerly looking forward to the code！Thanks a lot!

**Comment by kentsommer** [comment]
I'm closing this out to clean up my open issues.
